In [4]:
import torch

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [5]:
x = torch.zeros([2,5])
print(x)
x.shape

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


torch.Size([2, 5])

In [7]:
y = torch.rand([2,5])
print(y)

tensor([[0.2024, 0.2462, 0.2846, 0.4418, 0.3600],
        [0.5155, 0.9565, 0.2569, 0.9971, 0.3476]])


In [8]:
y.view([1,10])


tensor([[0.2024, 0.2462, 0.2846, 0.4418, 0.3600, 0.5155, 0.9565, 0.2569, 0.9971,
         0.3476]])

In [10]:
y=y.view([1,10])